In [ ]:
import numpy as np
import pandas as pd

In [ ]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [ ]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [ ]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [ ]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

first date dtype is object firstly changing it into datetime

In [ ]:
date['date'] = pd.to_datetime(date['date'])

In [ ]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

How to extract year...

In [ ]:
date['date_year'] = date['date'].dt.year

In [ ]:
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

Extracting month

In [ ]:
date['date_month_name'] = date['date'].dt.month_name()

In [ ]:
date.head()

        date  product_id  city_id  orders  date_year date_month_name
0 2019-12-10        5628       25       3       2019        December
1 2018-08-15        3646       14     157       2018          August
2 2018-10-23        1859       25       1       2018         October
3 2019-08-17        7292       25       1       2019          August
4 2019-01-06        4344       25       3       2019         January

Extracting Days

In [ ]:
date['date_day'] = date['date'].dt.day

In [ ]:
date.head()

        date  product_id  city_id  orders  date_year date_month_name  date_day
0 2019-12-10        5628       25       3       2019        December        10
1 2018-08-15        3646       14     157       2018          August        15
2 2018-10-23        1859       25       1       2018         October        23
3 2019-08-17        7292       25       1       2019          August        17
4 2019-01-06        4344       25       3       2019         January         6

days of week

In [ ]:
date['date_dow'] = date['date'].dt.dayofweek

In [ ]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,December,10,1
1,2018-08-15,3646,14,157,2018,August,15,2
2,2018-10-23,1859,25,1,2018,October,23,1
3,2019-08-17,7292,25,1,2019,August,17,5
4,2019-01-06,4344,25,3,2019,January,6,6

days of week

In [ ]:
date['date_dow_name'] = date['date'].dt.day_name()

In [ ]:
date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year date_month_name  date_day  date_dow date_dow_name
0 2019-12-10       2019        December        10         1       Tuesday
1 2018-08-15       2018          August        15         2     Wednesday
2 2018-10-23       2018         October        23         1       Tuesday
3 2019-08-17       2019          August        17         5      Saturday
4 2019-01-06       2019         January         6         6        Sunday

weekends

In [ ]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0)

In [ ]:
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,December,10,1,Tuesday,0
1,2018-08-15,2018,August,15,2,Wednesday,0
2,2018-10-23,2018,October,23,1,Tuesday,0
3,2019-08-17,2019,August,17,5,Saturday,1
4,2019-01-06,2019,January,6,6,Sunday,1

ectracting quarter

In [ ]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,quarter
0,2019-12-10,2019,December,10,1,Tuesday,0,4
1,2018-08-15,2018,August,15,2,Wednesday,0,3
2,2018-10-23,2018,October,23,1,Tuesday,0,4
3,2019-08-17,2019,August,17,5,Saturday,1,3
4,2019-01-06,2019,January,6,6,Sunday,1,1

extracting semester

In [ ]:
date['semester'] = np.where(date['quarter'].isin([1,2]),1,2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,quarter,semester
0,2019-12-10,2019,December,10,1,Tuesday,0,4,2
1,2018-08-15,2018,August,15,2,Wednesday,0,3,2
2,2018-10-23,2018,October,23,1,Tuesday,0,4,2
3,2019-08-17,2019,August,17,5,Saturday,1,3,2
4,2019-01-06,2019,January,6,6,Sunday,1,1,1

Exteact time elapsed between dates

In [ ]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 1, 8, 17, 10, 20, 198537)

In [ ]:
today - date['date']

0     2221 days 17:10:20.198537
1     2703 days 17:10:20.198537
2     2634 days 17:10:20.198537
3     2336 days 17:10:20.198537
4     2559 days 17:10:20.198537
                 ...
995   2649 days 17:10:20.198537
996   2590 days 17:10:20.198537
997   2438 days 17:10:20.198537
998   2503 days 17:10:20.198537
999   2277 days 17:10:20.198537
Name: date, Length: 1000, dtype: timedelta64[ns]

In [ ]:
(today - date['date']).dt.days

0      2221
1      2703
2      2634
3      2336
4      2559
       ...
995    2649
996    2590
997    2438
998    2503
999    2277
Name: date, Length: 1000, dtype: int64

months passed

In [ ]:
np.round((today - date['date']).dt.days / 30.44, 0)

0      73.0
1      89.0
2      87.0
3      77.0
4      84.0
       ...
995    87.0
996    85.0
997    80.0
998    82.0
999    75.0
Name: date, Length: 1000, dtype: float64

In [ ]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

converting the datatype

In [ ]:
time['date'] = pd.to_datetime(time['date'])

In [ ]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [ ]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

extracting time part

In [ ]:
time['time'] = time['date'].dt.time

In [ ]:
time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

time differences

In [ ]:

today - time['date']

0     4407 days 16:20:20.198537
1     4271 days 17:30:20.198537
2     4757 days 16:49:20.198537
3     4059 days 16:39:20.198537
4     4456 days 17:59:20.198537
                 ...
995   5046 days 16:20:20.198537
996   4367 days 17:56:20.198537
997   4832 days 17:33:20.198537
998   4948 days 17:36:20.198537
999   4220 days 17:45:20.198537
Name: date, Length: 1000, dtype: timedelta64[ns]

in seconds

In [ ]:
(today - time['date']) /np.timedelta64(1, 's')

0      3.808236e+08
1      3.690774e+08
2      4.110654e+08
3      3.507576e+08
4      3.850632e+08
           ...
995    4.360332e+08
996    3.773734e+08
997    4.175480e+08
998    4.275706e+08
999    3.646719e+08
Name: date, Length: 1000, dtype: float64

in minutes

In [ ]:
(today - time['date']) /np.timedelta64(1, 'm')

0      6.347060e+06
1      6.151290e+06
2      6.851089e+06
3      5.845959e+06
4      6.417719e+06
           ...
995    7.267220e+06
996    6.289556e+06
997    6.959133e+06
998    7.126176e+06
999    6.077865e+06
Name: date, Length: 1000, dtype: float64

in hours

In [ ]:
(today - time['date'])/np.timedelta64(1,'h')

0      105784.338944
1      102521.505611
2      114184.822277
3       97432.655611
4      106961.988944
           ...
995    121120.338944
996    104825.938944
997    115985.555611
998    118769.605611
999    101297.755611
Name: date, Length: 1000, dtype: float64